- name: Install LAST
  apt:
    name: last-align
    state: latest

- name: Install LAST
  apt:
    name: unzip
    state: latest

- name: Download ARGANNOT LAST db
  get_url:
    url: https://drive.google.com/file/d/151E0pdkMe_ewoo82KQHOVIHt7iNXto_Y/view?usp=sharing
    dest: /home/ubuntu/
    mode: '0777'

- name: Extract ARGANNOT LAST db from archive
  unarchive:
    src: /home/ubuntu/arg_annot_db.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
  become_user: ubuntu

- name: Download Resfinder LAST db
  get_url:
    url: https://drive.google.com/file/d/1-Sf4qjzchbBaxRifEoZlgVvDGWcibSRj/view?usp=sharing
    dest: /home/ubuntu/
    mode: '0777'

- name: Extract Resfinder LAST db from archive
  unarchive:
    src: /home/ubuntu/resfinderdb.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
  become_user: ubuntu

- name: Download AMRFinder LAST db
  get_url:
    url: https://drive.google.com/file/d/1Y0TwKLSm3m71Q_gNQn8CFc-OONd8_e5a/view?usp=sharing
    dest: /home/ubuntu/
    mode: '0777'

- name: Extract AMRFinder LAST db from archive
  unarchive:
    src: /home/ubuntu/AMRdb.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
  become_user: ubuntu
