- name: Install LAST
  apt:
    name: last-align
    state: latest

- name: Install LAST
  apt:
    name: unzip
    state: latest

- name: Download ARGANNOT LAST db
  shell: wget -P /home/ubuntu/ -O arg_annot_db.tar.gz https://uni-bielefeld.sciebo.de/s/zjeWBhdbyVHMVPI/download

- name: Extract ARGANNOT LAST db from archive
  unarchive:
    src: /home/ubuntu/arg_annot_db.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
  become_user: ubuntu

- name: Download ARGANNOT LAST db
  shell: wget -P /home/ubuntu/ -O resfinderdb.tar.gz https://uni-bielefeld.sciebo.de/s/OGIrQkW7LP4mQFS/download

- name: Extract Resfinder LAST db from archive
  unarchive:
    src: /home/ubuntu/resfinderdb.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
  become_user: ubuntu

- name: Download ARGANNOT LAST db
  shell: wget -P /home/ubuntu/ -O AMRdb.tar.gz https://uni-bielefeld.sciebo.de/s/lS4UYxyLDVOeWfC/download

- name: Extract AMRFinder LAST db from archive
  unarchive:
    src: /home/ubuntu/AMRdb.tar.gz
    dest: /home/ubuntu/
    remote_src: yes
  become_user: ubuntu
